-- AlterTable
ALTER TABLE `User` ADD COLUMN `contact` VARCHAR(255) NOT NULL DEFAULT '0000000000',
    ADD COLUMN `pays` VARCHAR(255) NOT NULL DEFAULT 'CI',
    ADD COLUMN `role` VARCHAR(65) NOT NULL DEFAULT 'root';
